### ISSUE TITLE
Please update HomeManager module to support the new theming

### ISSUE THREAD

**Issue by Luk45135** [abenz1267/walker#90] opened 2024-08-03 14:16 UTC
`error: getting status of '/nix/store/3nm8qlg1zjbp91wmqdjb1db3nzn3irlc-source/ui/themes/style.default.css': No such file or directory`
HomeManager module tries to read style.default.css which doesn't exist anymore.
Thanks

**Comment by abenz1267** [comment] 2024-08-04 08:17
fixed

**Comment by Luk45135** [comment] 2024-08-04 09:37
```
error: attribute 'style' missing
┃ 
┃        at /nix/store/pf9ja9q8k8kdf8krihnhsmzrpx85pkfm-source/nix/hm-module.nix:39:39:
┃ 
┃            38|       "walker/config.json".text = mkIf (cfg.config != {}) (builtins.toJSON cfg.config);
┃            39|       "walker/style.css".text = mkIf (cfg.style != {}) cfg.style;
┃              |                                       ^
┃            40|     };
```

hm-module expects `config.programs.walker.style` to exist when it's empty or not set

**Comment by AlxTray** [comment] 2024-08-04 14:32
In regards to this, is there a way of Walker picking up the old config.json and style.css under .config/walker or is it now better to just define the config and style files under themes directory through home manager manually? As now my walker is defaulting to the catppuccin theme not how I have it setup in home manager.

**Comment by abenz1267** [comment] 2024-08-04 14:51
You have to define the layout and css in the themes directory, yes. `themes/yourtheme.<ext>` and `themes/yourtheme.css`. Then just set `"theme": "yourtheme"` in your config.

**Comment by AlxTray** [comment] 2024-08-05 15:12
Is it possible for the style option line in the hm_module.nix file to be removed, as style.css in the root config directory does nothing now right? As its currently a catch 22 of it saying style option does not exist but then when you omit it it looks for the default style and then fails because of that.

**Comment by AlxTray** [comment] 2024-08-05 15:25
Ah sorry, thought you were maintaining the Nix stuff as only found this recently

**Comment by diniamo** [comment] 2024-08-05 16:29
#92 should have everything that's missing, please test

**Comment by Luk45135** [comment] 2024-08-05 22:29
So it "works" now, but (maybe a me problem) the themes are wonky on my machine.
![2024-08-06T00:19:55,769115632+02:00](https://github.com/user-attachments/assets/43af2a15-b457-4ea0-ad13-44a23136d2f3)
![2024-08-06T00:18:43,758389152+02:00](https://github.com/user-attachments/assets/488bb22d-3016-49e3-b679-9e2eea248ade)
also maybe unrelated, but `sudo systemctl list-unit-files | grep walker` returns nothing even though runAsService is set to true.

**Comment by abenz1267** [comment] 2024-08-06 05:06
That's because Walker doesn't exist in a vacuum and by nature it's using your systems GTK theme. The styling you apply in Walker just overrides that.

I'm actually thinking about just hard resetting everything, so something like in your screenshot won't happen. Not sure yet. 

Closing this, since the issue is solved.

**Closed by abenz1267** 2024-08-06 05:06 UTC

**Comment by abenz1267** [comment] 2024-08-06 05:32
default styles should work better now.

**Comment by diniamo** [comment] 2024-08-06 06:19
@Luk45135 it doesn't return anything because it's a user service

**Comment by Luk45135** [comment] 2024-08-06 09:37
@diniamo Thanks for the clarification i'm still learning this rabbit hole that is nix.
As for the gtk theming, i can understand that in the kanagawa theme that everything is dark because i forced it, but i don't understand the apparent light theme with catppuccin.

```nix
qt = {
    enable = true;
    platformTheme.name = "adwaita";
    style = {
      name = "adwaita-dark";
      # package = pkgs.adwaita-qt;
    };
  };
  gtk = {
    enable = true;
    font = {
      name = "Noto";
      size = 12;
    };
    theme = {
      package = pkgs.adw-gtk3;
      name = "adw-gtk3";
    };
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus";
    };
    gtk3.extraConfig = {
      gtk-application-prefer-dark-theme=1;
    };
    gtk4.extraConfig = {
      gtk-application-prefer-dark-theme=1;
    };

  };
  
  dconf.settings = {
    "org/gnome/desktop/interface" = {
      color-scheme = "prefer-dark";
    };
  };
```
Thanks for your work!

**Comment by abenz1267** [comment] 2024-08-06 09:41
Walker doesn't differentiate between your systems dark/light theme. With the latest version your system theme should be ignored/reset for Walker completely, so only the styles you set are... set.

**Comment by Luk45135** [comment] 2024-08-06 10:54
@abenz1267 Thanks, works like a charm, finally ready to switch to walker from rofi.
