### ISSUE TITLE
Sometimes it doesn't show any results

### ISSUE THREAD

**Issue by deimoss123** [abenz1267/walker#150] opened 2024-11-05 13:36 UTC
**Describe the bug**
Sometimes when opening walker, it only shows the search box without any results.

**Version**
walker-bin 0.8.3-1 from AUR.

**Minimal Config**
Default config with kanagawa theme.

**To Reproduce**
Not sure, it just happens randomly when opening walker. Most of the times it works as expected.

**Expected behavior**
For it to show results and for search to work.

**Screenshots**
![image](https://github.com/user-attachments/assets/0fc535da-61c2-4c61-8798-8cb02648d064)
![image](https://github.com/user-attachments/assets/52b34166-39e1-416d-877d-baef82f4a05e)
![image](https://github.com/user-attachments/assets/bd22cc75-23bc-4cbb-8e67-0507204d85fe)

**Desktop**
 - OS Arch
 - DE Hyprland

**Additional context**
I am not running walker as a service and I'm running it with `walker -m applications,calc`.

I was able to catch the bug while running it through the terminal. Here's the output:
```
➜  ~ walker -m applications,calc
WARN Theme parser error: gtk.css:7912:18-22: Expected a number priority=4 code_file=../gtk/gtk/gtkcssprovider.c code_line=192 code_func=gtk_css_provider_parsing_error glib_domain=Gtk
WARN Theme parser error: gtk.css:7924:18-22: Expected a number priority=4 code_file=../gtk/gtk/gtkcssprovider.c code_line=192 code_func=gtk_css_provider_parsing_error glib_domain=Gtk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 570 Series (RADV POLARIS10)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: Failed to find vkGetDeviceProcAddr in layer "/usr/lib/amdvlk64.so" priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: vkCreateDevice layer callstack setup to: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Application> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Loader> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Device> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:        Using "AMD Radeon RX 570 Series (RADV POLARIS10)" with driver: "/usr/lib/libvulkan_radeon.so" priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
```

**Comment by abenz1267** [comment] 2024-11-06 06:57
I could not replicate this on my system.

I've just discovered a few Vulkan related GTK bugs, this MIGHT also be one.... could you try running `GSK_RENDERER=ngl walker -m applications,calc`?

**Comment by deimoss123** [comment] 2024-11-06 11:24
The vulcan messages seem to go away when running with `GSK_RENDERER=ngl`. However the bug still persists. Another thing I found is that when there aren't any results, after a while it starts showing results, but they are cut off.

![image](https://github.com/user-attachments/assets/9ad7998e-296e-483c-9a3f-ad6f5c6dff4c)
![image](https://github.com/user-attachments/assets/43fd3e79-19e8-45c1-afe6-aa30249d5f5f)

There is also this gtk css warning, maybe could be related.
```
WARN Theme parser error: gtk.css:7912:18-22: Expected a number priority=4 code_file=../gtk/gtk/gtkcssprovider.c code_line=192 code_func=gtk_css_provider_parsing_error glib_domain=Gtk
WARN Theme parser error: gtk.css:7924:18-22: Expected a number priority=4 code_file=../gtk/gtk/gtkcssprovider.c code_line=192 code_func=gtk_css_provider_parsing_error glib_domain=Gtk
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
```

Could be worth mentioning that I use a custom GTK theme ([Gruvbox](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme)).

**Comment by abenz1267** [comment] 2024-11-06 12:45
Have you tried reproducing the issue with another GTK theme?

**Comment by deimoss123** [comment] 2024-11-06 13:29
Yes, I tried it with both Adwaita and Breeze. 

This screenshot is with Breeze Dark. Same issue, however it seems that it's being cut off more that before.
![image](https://github.com/user-attachments/assets/04b2782b-c2b2-437b-9a9e-0b7b99a63a0f)

On Adwaita, I couldn't reproduce the cutting off bug, however I did still get the regular "search box without results" bug from the first message.
![image](https://github.com/user-attachments/assets/0eb797ce-7c37-4307-8756-7fd28d502629)

**Comment by deimoss123** [comment] 2024-11-06 13:40
Btw I couldn't reproduce this behavior with the catppuccin theme. So it could just be an issue with the kanagawa theme.

**Comment by abenz1267** [comment] 2024-11-07 05:49
The kanagawa theme should be fixed now, you'd need to delete the thteme from your config folder though so walker can put in the new one. or you'd just add the missing bottom anchor in the layout file yourself.

For the "no results"-thing: i couldn't reproduce this so far...

**Comment by abenz1267** [comment] 2024-11-20 07:22
What's the state here? You still have issues? So far no other user reported this problem.

**Comment by abenz1267** [comment] 2024-11-20 14:41
I haven't changed anything that might have fixed it.

**Closed by abenz1267** 2024-11-20 14:41 UTC
