### ISSUE TITLE
Wlaker don't launch since the 0.10.14

### ISSUE THREAD

**Issue by Wateir** [abenz1267/walker#176] opened 2024-12-10 11:39 UTC
**Describe the bug**
start walker on terminal with `walker`
same issue with a bind onf hyprland.conf, just with less words

**Version**
`walker 0.10.14-1`

**Minimal Config**
[config.json](https://github.com/user-attachments/files/18078677/config.json)

[default.json](https://github.com/user-attachments/files/18078689/default.json)

[default.txt](https://github.com/user-attachments/files/18078708/default.txt)
*(Github don't support .css, so i rename it .txt)*

```.
├── config.json
└── themes
    ├── default.css
    └── default.json
```

**Expected behavior**
Walker launch

**Screenshots**
```ERROR config error="1 error(s) decoding:\n\n* 'builtins.applications.actions' expected a map, got 'bool'"
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 2060 priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 2060   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 2060 priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 2060   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: vkCreateDevice layer callstack setup to: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Application> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Loader> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Device> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:        Using "NVIDIA GeForce RTX 2060" with driver: "libGLX_nvidia.so.0" priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe60 pc=0xafa0fc]

goroutine 19 [running]:
github.com/abenz1267/walker/internal/ui.executeEvent.func1()
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/internal/ui/events.go:18 +0x7c
created by github.com/abenz1267/walker/internal/ui.executeEvent in goroutine 1
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/internal/ui/events.go:11 +0x6b
```

**Desktop**

- Arch
- Hyprland

**Additional context**
Maybe not the best place for this type of bug ? hope it's not the worst.

**Comment by abenz1267** [comment] 2024-12-10 12:40
Hi,

this is caused by your config being malformed + a missing nil protection.

I've fixed the missing nil constraint in the latest version, config you have to fix yourself.

```json
      "actions": true,
```

This is wrong for a few versions now, correct would be something like:

```json
      "actions": {
        "enabled": true,
        "hide_category": true,
        "hide_without_query": true
      },
```

**Comment by abenz1267** [comment] 2024-12-11 15:24
I'll close this, as it should be solved. Feel free to re-open, if not.

**Closed by abenz1267** 2024-12-11 15:24 UTC

**Comment by Wateir** [comment] 2024-12-11 17:44
```While parsing config: invalid character '"' after object key:value pair
panic: While parsing config: invalid character '"' after object key:value pair
	[recovered]
	panic: closure error: unexpected panic caught: While parsing config: invalid character '"' after object key:value pair
	
	
	Closure added at:
		main.main at /home/wateir/.cache/yay/walker/src/walker-0.10.14/cmd/walker.go:138
		runtime.main at /usr/lib/go/src/runtime/proc.go:272
		runtime.goexit at /usr/lib/go/src/runtime/asm_amd64.s:1700 [recovered]
	panic: closure error: unexpected panic caught: While parsing config: invalid character '"' after object key:value pair
	
	
	Closure added at:
		main.main at /home/wateir/.cache/yay/walker/src/walker-0.10.14/cmd/walker.go:138
		runtime.main at /usr/lib/go/src/runtime/proc.go:272
		runtime.goexit at /usr/lib/go/src/runtime/asm_amd64.s:1700

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc000234510)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:118 +0xe6
panic({0xc23900?, 0xc0002a2d10?})
	/usr/lib/go/src/runtime/panic.go:785 +0x132
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc0002344b0, {0xe91656, 0x1b}, {0xc000036a48, 0x1, 0x1})
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc0002344b0)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:122 +0xbc
panic({0xc23900?, 0xc0002a2d00?})
	/usr/lib/go/src/runtime/panic.go:785 +0x132
log.Panicln({0xc000036ca8?, 0xc0002a2cd0?, 0xc67d80?})
	/usr/lib/go/src/log/log.go:446 +0x5a
github.com/abenz1267/walker/internal/config.Get({0x1?, 0xc0002a2020?})
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/internal/config/config.go:356 +0x318
main.main.Activate.func5(0xc0002a4018)
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/internal/ui/ui.go:92 +0x9c
reflect.Value.call({0xc26900?, 0x115cf10?, 0x560c51?}, {0xe808f4, 0x4}, {0xc0002a4000, 0x1, 0xc00007a720?})
	/usr/lib/go/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0xc26900?, 0x115cf10?, 0xe02f00?}, {0xc0002a4000?, 0x115f530?, 0x38cb84a0?})
	/usr/lib/go/src/reflect/value.go:365 +0xb9
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_goMarshal(0x38db2830, 0x0, 0x1, 0x7fff80ffab80, 0xc0000061c0?, 0x38db21a0)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/glib/glib.go:306 +0x978
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_activate(0x38db21a0)
	_cgo_gotypes.go:13548 +0x3f
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate.func1(0x38db21a0)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x34
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate(0xc000223cf8)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x37
main.main.func3(0xc00011e070)
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/cmd/walker.go:230 +0x8fd
github.com/diamondburned/gotk4/pkg/gio/v2._gotk4_gio2_Application_ConnectCommandLine(0xc000037a20?, 0x38eb5c00, 0x38e0f820?)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio_export.go:1841 +0x102
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x38db21a0, 0x1, 0x38db69c0)
	_cgo_gotypes.go:14099 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x38db21a0, 0x1, 0x38db69c0)
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc000223cf8, {0xc0000241b0, 0x1, 0x1})
	/home/wateir/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1
main.main()
	/home/wateir/.cache/yay/walker/src/walker-0.10.14/cmd/walker.go:265 +0x845
 ```
	
My new config
[config.json](https://github.com/user-attachments/files/18099979/config.json)

**Comment by abenz1267** [comment] 2024-12-11 17:46
Install a proper json formatter. This has nothing to do with Walker. Fix you json.

**Comment by Wateir** [comment] 2024-12-11 22:21
Work great with a json correcly format, how you know it's the issue here

So next time i can resolve this myself

**Comment by abenz1267** [comment] 2024-12-12 05:55
`panic: While parsing config: invalid character '"' after object key:value pair`
