### ISSUE TITLE
hard crash back to display manager when Walker closes when running as a service

### ISSUE THREAD

**Issue by AlxTray** [abenz1267/walker#88] opened 2024-08-01 18:24 UTC
Just updated my nix flake, in turn updating Walker to the latest version as of an hour ago I believe, and when running Walker as a systemd service once an operation is completed or Walker is closed my wayland session crashes and I'm taken back to my display manager.

These are errors that I found in the systemd log for Walker, not sure if they are related:
`Aug 01 19:18:06 alxputer walker[1917]: error when running: event reading error: unable to read message header: read unix @->/run/user/1000/wayland-1: EOF
Aug 01 19:18:06 alxputer walker[1917]: INFO Error reading events from display: Broken pipe priority=5 code_file=../gdk/wayland/gdkeventsource.c code_line=116 code_func=gdk_event_source_check glib_domain=Gdk`

**Comment by abenz1267** [comment] 2024-08-01 18:26
can you show me your service file?

**Comment by AlxTray** [comment] 2024-08-01 18:30
`[Install]
WantedBy=graphical-session.target

[Service]
ExecStart=/nix/store/zryshs15cjl2sacfp926jagr7sklizav-walker-0.5.5/bin/walker --gapplication-service

[Unit]
Description=Walker - Application Runner`

You mean this?

**Comment by abenz1267** [comment] 2024-08-01 18:31
I don't think it matters.. but can u try 0.5.6?

**Comment by AlxTray** [comment] 2024-08-01 18:33
I'll update it from source but might take a bit to build

**Comment by abenz1267** [comment] 2024-08-01 18:34
the nix cache should be done in around 7 minutes.. so might be worth waiting for it.

**Comment by AlxTray** [comment] 2024-08-01 18:35
flake input for walker has updated, so I'll let you know once everything has rebuilt. Haven't got many changes so shouldn't take too long

**Comment by AlxTray** [comment] 2024-08-01 18:44
Just tested on latest, and same issue

**Comment by abenz1267** [comment] 2024-08-01 18:54
are you on hyprland? can you check if you get the same problem if you run walker via hyprlands `exec-once`?

The problem is: i can't debug this. Setting `context_aware` to `false` for the `applications` module, should at least not make it crash. but if you are on 0.5.6 you'd also need to disable the new `windows` module.

I'm on Arch, everything works fine here.

**Comment by abenz1267** [comment] 2024-08-01 18:59
another thing: can you run `walker -b` in a terminal and gimme the output? (while the service is running)

**Comment by AlxTray** [comment] 2024-08-01 19:15
yeah crashes each time when launched with the --gapplication-service flag, even when exec-once in Hyprland.

This is the output from walker -b:

Startup: 1722539252834933673
start run: 1722539252835050194

**Comment by abenz1267** [comment] 2024-08-01 19:17
what hyprland version are you on?

**Comment by AlxTray** [comment] 2024-08-01 19:20
master I would believe

**Comment by AlxTray** [comment] 2024-08-01 19:20
or at least builds from latest commit, I'm pretty sure

**Comment by abenz1267** [comment] 2024-08-01 19:21
so this means aquamarine .... can you try stable hyprland?

**Comment by AlxTray** [comment] 2024-08-01 19:23
I would have already been using aquamarine earlier today and was working fine

**Comment by abenz1267** [comment] 2024-08-01 19:24
but wayland things are in walker only since 0.5.4. so if it crashes since upating to 0.5.5/6 .... that might be related.

**Comment by AlxTray** [comment] 2024-08-01 19:27
Ah okay, I'll change to the Hyprland nixpkg instead of flake and see if anything changes

**Comment by abenz1267** [comment] 2024-08-01 19:32
I've just installed hyprland-git on arch myself.. and yeah. it crashes on there. so.... a hyprland bug?

**Comment by abenz1267** [comment] 2024-08-01 19:33
ok, according to hyprland discord that's a hyprland issue that's already known. closing.

**Closed by abenz1267** 2024-08-01 19:33 UTC

**Comment by AlxTray** [comment] 2024-08-01 19:39
Yep, it's Hyprland's fault, its working just fine on release 0.41.2

**Comment by AlxTray** [comment] 2024-08-01 19:40
Sorry for the time waste
