### ISSUE TITLE
vesktop launching under xwayland

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#116] opened 2024-08-22 13:06 UTC
**Describe the bug**
vesktop is lauched under xwayland instead of  native wayland, i assume this is a bug as it works when launched via terminal

**Version**
latest git build

**Minimal Config**
```json
{
  "list": {
    "height": 500
  },
  "search": {
    "placeholder": "Search"
  },
  "switcher": {
    "prefix": "/"
  },
  "ui": {
    "anchors": {
      "bottom": true,
      "top": true
    },
    "fullscreen": true,
    "width": 800
  },
  "websearch": {
    "prefix": "?"
  }
}
```

**To Reproduce**
Launch vektop with walker

**Expected behavior**
I expect vesktop to launch under wayland, I have the `NIXOS_OZONE_WL=1` env var set

**Screenshots**

**Desktop**
 - OS : NixOS
 - DE Hyprland

**Comment by abenz1267** [comment] 2024-08-22 13:26
Can't reproduce on Arch, i suspect an issue with your systems config. 

```
echo "--enable-features=UseOzonePlatform --ozone-platform-hint=auto" > ~/.config/vesktop-flags.conf
```

Ran Vesktop via Walker. Uses Wayland, confirmed by `hyprctl clients`.

**Comment by Ciflire** [comment] 2024-08-22 14:26
i'd say it's more a system specificity eventually more than an issue with my system config. I don't have the problem with wofi for example.

**Comment by abenz1267** [comment] 2024-08-22 14:30
Well, but you don't run wofi as a service. I assume your walker instance doesn't get the ozone config from nix in time.

**Comment by Ciflire** [comment] 2024-08-22 14:33
that's it, still wierd tho, service should be ran after user connection, and env var is set on system start

**Comment by abenz1267** [comment] 2024-08-22 14:36
Closing as it's not an issue with Walker.

**Closed by abenz1267** 2024-08-22 14:36 UTC

**Comment by Ciflire** [comment] 2024-08-22 17:05
So i got my answer, because it is a service ran by systemd, walker as a service will never get any environment variable. it will always get them from systemd, but systemd as first process is never started with env var
I do think though this will not only be a nix problem, only difference i guess is that many people use flags instead

**Comment by abenz1267** [comment] 2024-08-22 17:23
Yeah, always keep in mind that systemd-services are not really meant to be used to autostart gui applications, which walker is. anything around them will be funky.
