### ISSUE TITLE
Daily gapplication-service crashes

### ISSUE THREAD

**Issue by ItsLemmy** [abenz1267/walker#152] opened 2024-11-08 19:55 UTC
**Describe the bug**
Using:  walker -m clipboard
Module(s) not found
.⏎     

**Version**
0.8.8-git and 0.8.7

**Minimal Config**
Even with default config.

**Desktop**
 - Arch
 - Hyprland

**Comment by quadbyte** [comment] 2024-11-08 20:01
I'm not sure what happened, but it is now working again.   Keeping this open for a few days.

**Comment by quadbyte** [comment] 2024-11-10 14:06
Okay I figured what happened there.

Basically the clipboard module is only available when the background service is running.
If you run walker -m clipboard without having launcher --gapplication-service before end you will get "Module(s) not found"

Probably Walker crashed at some point and so I could not access my clipboard anymore.


I'm not sure what would be the best UX for this case, but I don't like it too much that is fails silently when using keybinds.  It was rather frustrating and it's not very good experience if you need to hop in a terminal and type the command by hand to check what error there is.

Maybe this is a good opportunity to implement basic error/status messages in the UI itself.
So if one was to call "walker -m clipboard" without the service running it would show a message:  "Clipboard module is unable until the walker service is running"  or something along theses lines.

Rofi is doing it , if your command fails to execute, you get a simple window with some error description and help.
![image](https://github.com/user-attachments/assets/6d17ef7b-36c3-43ec-9ea9-8ad60264b619)

You could probably also probably have the gapplication-service starts automatically if someone call one of the module that requires it to run: Clipboard and Windows (switcher)

**Comment by abenz1267** [comment] 2024-11-10 15:19
Starting it automatically is impossible, as it's up to the user how to even start it. Some people have a systemd service, i run `exec-once` in Hyprland. Not sure if I'm missing something rn, but i wouldn't know how to start it.

Would by nice to know why it crashed.

I thought about utilizing `notify-send` to send a notification when the service crashes. I think that'd be good in general.

I agree, a more UX friendly failure UI would be good.

**Comment by abenz1267** [comment] 2024-11-16 07:40
Hey, depends on how you launch it. Since it's just writing to stdout ... i assume you should be able to retrieve it?

How often does that happen? You'd ofc also just open up a terminal and let it run in there until it crashes.

**Comment by quadbyte** [comment] 2024-11-16 13:30
❯ walker --gapplication-service
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [1] AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [1] AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [1] AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [1] AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: vkCreateDevice layer callstack setup to: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Application> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Loader> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Device> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:        Using "AMD Radeon RX 7800 XT (RADV NAVI32)" with driver: "/usr/lib/libvulkan_radeon.so" priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1692 code_func=gdk_vulkan_debug_report glib_domain=Gdk
panic: runtime error: slice bounds out of range [:-8]

goroutine 23 [running]:
github.com/neurlang/wayland/wl.(*BytePool).Take(0xc000428006?, 0xfffffffffffffff8)
        /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/utils.go:31 +0x9c
github.com/neurlang/wayland/wl.(*Context).readEvent(0xc00023e460)
        /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/event.go:74 +0x370
github.com/neurlang/wayland/wl.(*Context).run(0xc00023e460, 0x0)
        /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/context.go:165 +0x2d
github.com/neurlang/wayland/wl.(*Context).Run(...)
        /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/context.go:147
github.com/abenz1267/walker/internal/modules/windows/wlr.StartWM(0x9a9be5?, 0x0?)
        /home/runner/work/walker/walker/internal/modules/windows/wlr/wm.go:64 +0x17e
created by github.com/abenz1267/walker/internal/modules/windows.(*Windows).SetupData in goroutine 100
        /home/runner/work/walker/walker/internal/modules/windows/windows.go:34 +0x28

**Comment by quadbyte** [comment] 2024-11-16 13:36
Took less than an hour to get it to crash today.   Not sure what trigger the crash, I'll continue monitoring.

From what I remember from the last  hour (and what I can see was saved to the clipboard) I only used the default mode to run apps, and some copy/paste to the clipboard.

**Comment by abenz1267** [comment] 2024-11-16 16:58
Hm, i can't really digest what's causing the runtime error in the wayland library....

**Comment by quadbyte** [comment] 2024-11-16 17:27
Seems the lib receive a null sized event, and the allocation fails. 

```
	// subtract 8 bytes from header
	data := bytePool.Take(int(size) - 8)
```

I may have to open an issue upstream.

**Comment by abenz1267** [comment] 2024-11-16 17:49
Yeah, THAT i figured out as well, but I can't figure out why it works fine on my system. Like... i use my computer for like 52 hours per day and it never crashes.

**Comment by quadbyte** [comment] 2024-11-16 18:13
Do you use the windows switcher much?

**Comment by quadbyte** [comment] 2024-11-17 12:36
I believe I have found the main culprit to my crashes.
I have a custom walker module that use a bash script  and in some specific conditions the script might return nothing (ie : no columns separated by tabs)   Walker does not seems to validate the string that it receive from the script, so it crashs.

I get the following crash: 

> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 12 [running]:
> github.com/abenz1267/walker/internal/modules.Plugin.Entries({{{0x0, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, 0x1, {0xc0002fc1a0, 0x7}, ...}, ...}, ...}, ...)
> 	/home/runner/work/walker/walker/internal/modules/plugins.go:120 +0xaea
> github.com/abenz1267/walker/internal/ui.processAsync.func3({0xe3a748, 0xc000316410}, 0x0?, {0x0, 0x0}, {0xe3c6a0, 0xc000002d80})
> 	/home/runner/work/walker/walker/internal/ui/interactions.go:733 +0xe4
> created by github.com/abenz1267/walker/internal/ui.processAsync in goroutine 90
> 	/home/runner/work/walker/walker/internal/ui/interactions.go:726 +0x93f


Step to reproduce.
1- Add this module to walker's config.json
```
    {
      "name": "testmod",
      "placeholder": "Hello World",
      "keep_sort": true,
      "prefix": "~",
      "terminal": true,
      "refresh": true,
      "label_column": 1,
      "result_column": 2,
      "separator": "\t",
      "src_once": "echo -e 'foo'",
      "cmd": "something"
    }
```
2- Start the service in a terminal:   
> walker --gapplication-service

3- In another terminal start the module, and it will crash instantly.
> walker -m testmod

It would be nice to improve overall stability by bullet proofing the code from invalid input.

**Comment by abenz1267** [comment] 2024-11-17 17:57
Hm, yeah.. that looks odd. But isn't that just a mis-configuration? What would you like the output to be in that case, since an explicit label column and result column is specified. just `foo`?

**Comment by quadbyte** [comment] 2024-11-18 13:01
Of course this can be fixed in the script itself (which I did for now)

But I strongly believe Walker should avoid crashing at any cost.,  as it is running a service, and it holds the clipboard. It's kind of frustrating to realize a bunch of stuff you copied to the clipboard is actually gone, and that the program has crashed 15 minutes ago.

I would just add some validation code to the input to avoid crashing and would fallback to display the usual No Result.

Does that make sense to you ?

**Comment by abenz1267** [comment] 2024-11-18 14:35
Yes, it does. I just wasn't sure what a user would expect for "broken" entries. I'll just discard them then.

**Comment by abenz1267** [comment] 2024-11-18 14:38
Should be fixed.

**Comment by quadbyte** [comment] 2024-11-19 12:31
Thanks!  Closing this one. Will keep an eye on stability on my setup.

**Closed as completed by quadbyte** 2024-11-19 12:31 UTC
